### ISSUE TITLE
the training strategy

### ISSUE THREAD

**Issue by yihong-97** [LTTM/LSR#1]
Thank you for your great work.
I found two papers （LSR and LSR+） pointing to this project, which method is the current project?

and I run this code and follow the [strategy](https://github.com/LTTM/LSR/blob/ab204895a86160a5d278fe3cee14c11532251218/README.md) of GTA5-to-Cityscapes with ResNet101 to train a uda models, but mIoU is much lower than the paper, is there any wrong parameter setting?

thanks

**Comment by barbafrank** [comment]
Hi, thank you for your kind words.
The code is the same as the one used in the results for the paper, there might be a slight variability in the performance due to CuDNNs non-deterministic routines, but it shouldn't change much.
In the gta2city (with pretrain) setup you should be able to achieve the 46+% mIoU score.
What was the score you have obtained?

**Comment by barbafrank** [comment]
Hi again, I checked over the code - among a couple of minor typos that were introduced in a code refactoring (which should now be fixed) there was also a missing 0 in the default adaptation rounds number (was 1, instead of 10).
Could you verify whether with a longer training your results match?

**Comment by yihong-97** [comment]
Hi, thanks for your quick response.
As you said, I use the previous strategy (rounds number is 1), and the mIoU score was only 42.5.
I will try your latest version of the code, thanks :)
